import type { AppState } from './types'

export function createSeedState(): AppState {
  return {
    currentUser: {
      id: 'user-maya',
      name: 'Maya Brooks',
      headline: 'Community builder learning design, Spanish, and smarter systems',
      city: 'Indianapolis',
      email: 'maya@skillswap.app',
      phone: '(317) 555-0184',
      about:
        'I trade event strategy, outreach planning, and launch support for design feedback, language practice, and technical coaching.',
      wallet: 950,
      verified: true,
      role: 'member',
      evidence: ['Volunteer portfolio', 'Three local references'],
      interests: ['Product design', 'Spanish fluency', 'Creator workflows'],
      availability: ['Tue 6:30 PM', 'Thu 7:00 PM', 'Sat 10:00 AM'],
      listings: [
        {
          id: 'maya-listing-1',
          title: 'Community Launch Planning',
          category: 'Strategy',
          description:
            'A focused session to map outreach, partnerships, and event momentum for a new idea.',
          price: 65,
          unit: '/ session',
          mode: 'hybrid',
          tags: ['community', 'launch', 'events'],
        },
        {
          id: 'maya-listing-2',
          title: 'Volunteer Operations Cleanup',
          category: 'Operations',
          description:
            'I turn loose volunteer workflows into a clear checklist, roster, and communication plan.',
          price: 80,
          unit: '/ sprint',
          mode: 'online',
          tags: ['operations', 'systems', 'coordination'],
        },
      ],
    },
    providers: [
      {
        id: 'aisha-grant',
        name: 'Aisha Grant',
        headline: 'UX audits, portfolio reviews, and product design coaching',
        city: 'Indianapolis',
        coverage: ['Indianapolis', 'Fishers', 'Carmel'],
        bio: 'Former startup product designer helping early-career builders sharpen flows, visuals, and storytelling.',
        deliveryModes: ['online', 'hybrid'],
        rating: 4.9,
        reviewCount: 48,
        responseTime: 'within 2 hours',
        completedJobs: 112,
        trustBadges: ['Identity checked', 'Portfolio verified', 'Top rated'],
        evidence: ['Case studies linked', 'Figma community profile'],
        availability: ['Mon 6:30 PM', 'Wed 7:00 PM', 'Sat 11:00 AM'],
        featured: true,
        listings: [
          {
            id: 'aisha-listing-1',
            title: 'Portfolio Critique Sprint',
            category: 'Design',
            description:
              'A practical review of case studies, layout, storytelling, and interview readiness.',
            price: 75,
            unit: '/ session',
            mode: 'online',
            tags: ['ui', 'ux', 'portfolio', 'figma'],
          },
          {
            id: 'aisha-listing-2',
            title: 'Product Design Deep Dive',
            category: 'Design',
            description:
              'Collaborative workshop for flows, wireframes, research framing, and prototype direction.',
            price: 130,
            unit: '/ workshop',
            mode: 'hybrid',
            tags: ['product', 'research', 'prototype'],
          },
        ],
      },
      {
        id: 'marco-bennett',
        name: 'Marco Bennett',
        headline: 'Furniture assembly and small home fixes without the headache',
        city: 'Carmel',
        coverage: ['Carmel', 'Indianapolis', 'Fishers', 'Westfield'],
        bio: 'Trusted local fixer for flat-pack builds, wall patching, and practical handyman tasks.',
        deliveryModes: ['in-person', 'hybrid'],
        rating: 4.8,
        reviewCount: 61,
        responseTime: 'same day',
        completedJobs: 143,
        trustBadges: ['Background checked', 'Top rated', 'Insured'],
        evidence: ['Insurance certificate on file', 'Project photo gallery'],
        availability: ['Tue 5:30 PM', 'Fri 4:00 PM', 'Sun 9:00 AM'],
        featured: true,
        listings: [
          {
            id: 'marco-listing-1',
            title: 'Flat-pack Assembly Rescue',
            category: 'Home Services',
            description:
              'Beds, desks, shelves, and dressers assembled cleanly with packaging hauled away.',
            price: 95,
            unit: '/ visit',
            mode: 'in-person',
            tags: ['assembly', 'furniture', 'home'],
          },
          {
            id: 'marco-listing-2',
            title: 'Patch and Paint Refresh',
            category: 'Home Services',
            description:
              'Fast cosmetic wall fixes for rentals, studios, and move-out touchups.',
            price: 110,
            unit: '/ visit',
            mode: 'hybrid',
            tags: ['repair', 'paint', 'rental'],
          },
        ],
      },
      {
        id: 'priya-raman',
        name: 'Priya Raman',
        headline: 'Coding mentor for dashboards, React, Python, and data storytelling',
        city: 'Bloomington',
        coverage: ['Bloomington', 'Indianapolis'],
        bio: 'Engineer and mentor translating messy goals into useful products, better code, and calmer debugging sessions.',
        deliveryModes: ['online', 'hybrid'],
        rating: 4.95,
        reviewCount: 34,
        responseTime: 'within 1 hour',
        completedJobs: 87,
        trustBadges: ['Identity checked', 'Top rated', 'Mentor approved'],
        evidence: ['GitHub profile linked', 'Speaking reel attached'],
        availability: ['Mon 8:00 PM', 'Thu 6:00 PM', 'Sat 1:30 PM'],
        featured: true,
        listings: [
          {
            id: 'priya-listing-1',
            title: 'React and TypeScript Coaching',
            category: 'Development',
            description:
              'Pair-programming support for components, state design, debugging, and delivery confidence.',
            price: 120,
            unit: '/ session',
            mode: 'online',
            tags: ['react', 'typescript', 'frontend'],
          },
          {
            id: 'priya-listing-2',
            title: 'Python Data Clinic',
            category: 'Development',
            description:
              'Bring a messy dataset or dashboard idea and leave with a cleaner plan and working direction.',
            price: 105,
            unit: '/ session',
            mode: 'hybrid',
            tags: ['python', 'data', 'analytics'],
          },
        ],
      },
      {
        id: 'elena-torres',
        name: 'Elena Torres',
        headline: 'Spanish conversation practice and bilingual client support',
        city: 'Indianapolis',
        coverage: ['Indianapolis', 'Greenwood', 'Online'],
        bio: 'Warm, structured language coach helping adults speak more naturally in real-life and work settings.',
        deliveryModes: ['online', 'hybrid'],
        rating: 4.7,
        reviewCount: 53,
        responseTime: 'within 3 hours',
        completedJobs: 130,
        trustBadges: ['Identity checked', 'Community favorite'],
        evidence: ['Teaching references', 'Lesson samples available'],
        availability: ['Tue 6:00 PM', 'Thu 8:00 PM', 'Sun 2:00 PM'],
        featured: false,
        listings: [
          {
            id: 'elena-listing-1',
            title: 'Spanish Conversation Lab',
            category: 'Language',
            description:
              'Low-pressure speaking practice built around your goals, topics, and confidence level.',
            price: 42,
            unit: '/ session',
            mode: 'online',
            tags: ['spanish', 'conversation', 'fluency'],
          },
          {
            id: 'elena-listing-2',
            title: 'Bilingual Client Call Prep',
            category: 'Language',
            description:
              'Practice introductions, questions, and follow-ups before a real meeting or presentation.',
            price: 70,
            unit: '/ prep session',
            mode: 'hybrid',
            tags: ['business', 'translation', 'presentation'],
          },
        ],
      },
      {
        id: 'noah-campbell',
        name: 'Noah Campbell',
        headline: 'Video edits, reels, and motion graphics for small brands',
        city: 'Louisville',
        coverage: ['Louisville', 'Global'],
        bio: 'Fast-moving editor for launch clips, creator packages, and polished short-form storytelling.',
        deliveryModes: ['online'],
        rating: 4.85,
        reviewCount: 39,
        responseTime: 'within 4 hours',
        completedJobs: 94,
        trustBadges: ['Portfolio verified', 'Top rated'],
        evidence: ['Showreel linked', 'Client credits attached'],
        availability: ['Daily after 1:00 PM'],
        featured: true,
        listings: [
          {
            id: 'noah-listing-1',
            title: 'Short-form Video Edit',
            category: 'Media',
            description:
              'Cuts, captions, pacing, and export prep for social clips that need to move fast.',
            price: 90,
            unit: '/ video',
            mode: 'online',
            tags: ['video', 'editing', 'reels'],
          },
          {
            id: 'noah-listing-2',
            title: 'Launch Reel Motion Pack',
            category: 'Media',
            description:
              'A polished announcement reel with simple animation, type, and branded motion.',
            price: 180,
            unit: '/ package',
            mode: 'online',
            tags: ['motion', 'launch', 'brand'],
          },
        ],
      },
      {
        id: 'simone-patel',
        name: 'Simone Patel',
        headline: 'Wellness workshops and CPR refreshers for teams and families',
        city: 'Indianapolis',
        coverage: ['Indianapolis', 'Greenwood', 'Fishers'],
        bio: 'Licensed instructor designing calm, practical safety and wellness sessions for real-world use.',
        deliveryModes: ['in-person', 'hybrid'],
        rating: 4.92,
        reviewCount: 27,
        responseTime: 'within 6 hours',
        completedJobs: 58,
        trustBadges: ['License verified', 'Background checked'],
        evidence: ['BLS and CPR instructor card', 'Liability insurance on file'],
        availability: ['Wed 5:00 PM', 'Sat 9:30 AM'],
        featured: false,
        listings: [
          {
            id: 'simone-listing-1',
            title: 'CPR Refresher Session',
            category: 'Wellness',
            description:
              'Hands-on refresher for households, caregivers, and small teams who want confidence in emergencies.',
            price: 85,
            unit: '/ session',
            mode: 'in-person',
            tags: ['cpr', 'safety', 'training'],
          },
          {
            id: 'simone-listing-2',
            title: 'Stress Reset Workshop',
            category: 'Wellness',
            description:
              'A practical workshop on recovery habits, pacing, and burnout prevention for busy groups.',
            price: 125,
            unit: '/ workshop',
            mode: 'hybrid',
            tags: ['wellness', 'stress', 'workshop'],
          },
        ],
      },
    ],
    reviews: [
      {
        id: 'review-1',
        providerId: 'aisha-grant',
        providerName: 'Aisha Grant',
        author: 'Tessa N.',
        rating: 5,
        text: 'Aisha turned my scattered portfolio into a story that finally made sense to recruiters.',
        verified: true,
        serviceTitle: 'Portfolio Critique Sprint',
        createdAt: '2026-04-12T14:15:00.000Z',
      },
      {
        id: 'review-2',
        providerId: 'marco-bennett',
        providerName: 'Marco Bennett',
        author: 'Devon R.',
        rating: 5,
        text: 'Marco assembled two rooms worth of furniture faster than I expected and cleaned everything up.',
        verified: true,
        serviceTitle: 'Flat-pack Assembly Rescue',
        createdAt: '2026-04-10T16:40:00.000Z',
      },
      {
        id: 'review-3',
        providerId: 'priya-raman',
        providerName: 'Priya Raman',
        author: 'Leah S.',
        rating: 5,
        text: 'Priya explained state management in a way that instantly made my project less chaotic.',
        verified: true,
        serviceTitle: 'React and TypeScript Coaching',
        createdAt: '2026-04-18T18:05:00.000Z',
      },
      {
        id: 'review-4',
        providerId: 'elena-torres',
        providerName: 'Elena Torres',
        author: 'Mina G.',
        rating: 4,
        text: 'I finally felt comfortable speaking out loud instead of freezing halfway through sentences.',
        verified: true,
        serviceTitle: 'Spanish Conversation Lab',
        createdAt: '2026-04-20T12:20:00.000Z',
      },
      {
        id: 'review-5',
        providerId: 'simone-patel',
        providerName: 'Simone Patel',
        author: 'Marcus P.',
        rating: 5,
        text: 'Simone kept the CPR session practical, calm, and easy to remember.',
        verified: true,
        serviceTitle: 'CPR Refresher Session',
        createdAt: '2026-04-11T09:45:00.000Z',
      },
      {
        id: 'review-6',
        providerId: 'noah-campbell',
        providerName: 'Noah Campbell',
        author: 'Ivy K.',
        rating: 5,
        text: 'Noah’s edit tightened our launch clip without losing the personality of the brand.',
        verified: true,
        serviceTitle: 'Short-form Video Edit',
        createdAt: '2026-04-08T11:15:00.000Z',
      },
    ],
    bookings: [
      {
        id: 'booking-1',
        providerId: 'elena-torres',
        providerName: 'Elena Torres',
        listingId: 'elena-listing-1',
        serviceTitle: 'Spanish Conversation Lab',
        date: '2026-05-02',
        time: '18:00',
        location: 'Online session',
        amount: 42,
        status: 'Confirmed',
        note: 'Focus on introductions, client conversations, and confidence building.',
      },
      {
        id: 'booking-2',
        providerId: 'marco-bennett',
        providerName: 'Marco Bennett',
        listingId: 'marco-listing-1',
        serviceTitle: 'Flat-pack Assembly Rescue',
        date: '2026-05-05',
        time: '10:30',
        location: 'Indianapolis',
        amount: 95,
        status: 'Pending',
        note: 'Bedroom dresser and two side tables.',
      },
      {
        id: 'booking-3',
        providerId: 'priya-raman',
        providerName: 'Priya Raman',
        listingId: 'priya-listing-1',
        serviceTitle: 'React and TypeScript Coaching',
        date: '2026-04-22',
        time: '19:00',
        location: 'Online session',
        amount: 120,
        status: 'Completed',
        note: 'Refactor a dashboard and clean up component state.',
      },
    ],
    messages: [
      {
        id: 'message-1',
        contactId: 'elena-torres',
        contactName: 'Elena Torres',
        direction: 'inbound',
        text: 'Happy to tailor our practice session around client calls if that helps.',
        timestamp: '2026-04-27T16:05:00.000Z',
      },
      {
        id: 'message-2',
        contactId: 'elena-torres',
        contactName: 'Elena Torres',
        direction: 'outbound',
        text: 'Yes please. I want to practice intros and follow-up questions.',
        timestamp: '2026-04-27T16:14:00.000Z',
      },
      {
        id: 'message-3',
        contactId: 'aisha-grant',
        contactName: 'Aisha Grant',
        direction: 'inbound',
        text: 'Send over your portfolio link whenever you are ready and I will prep notes.',
        timestamp: '2026-04-26T18:32:00.000Z',
      },
      {
        id: 'message-4',
        contactId: 'aisha-grant',
        contactName: 'Aisha Grant',
        direction: 'outbound',
        text: 'Perfect. I am especially looking for feedback on case study structure.',
        timestamp: '2026-04-26T18:40:00.000Z',
      },
    ],
    notifications: [
      {
        id: 'notification-1',
        title: 'Upcoming session confirmed',
        body: 'Elena confirmed your Spanish Conversation Lab for Fri, May 2 at 6:00 PM.',
        tone: 'success',
        createdAt: '2026-04-28T17:20:00.000Z',
        read: false,
      },
      {
        id: 'notification-2',
        title: 'Escrow protected payment',
        body: 'Your payment for Priya’s coaching session was released after completion.',
        tone: 'info',
        createdAt: '2026-04-23T13:10:00.000Z',
        read: false,
      },
      {
        id: 'notification-3',
        title: 'Welcome to Skillswap',
        body: 'Your profile, listings, and support inbox are ready to use.',
        tone: 'info',
        createdAt: '2026-04-21T10:00:00.000Z',
        read: true,
      },
    ],
    payments: [
      {
        id: 'payment-1',
        bookingId: 'booking-3',
        providerName: 'Priya Raman',
        amount: 120,
        fee: 10,
        method: 'Visa ending 2408',
        status: 'Released',
        createdAt: '2026-04-22T18:35:00.000Z',
      },
      {
        id: 'payment-2',
        bookingId: 'booking-1',
        providerName: 'Elena Torres',
        amount: 42,
        fee: 3,
        method: 'Skillswap balance',
        status: 'Held in escrow',
        createdAt: '2026-04-28T17:15:00.000Z',
      },
    ],
    supportMessages: [
      {
        id: 'support-1',
        role: 'assistant',
        text: 'I can help with refunds, missed sessions, suspicious activity, booking changes, or account questions. Tell me what happened.',
      },
    ],
    complaints: [
      {
        id: 'complaint-1',
        topic: 'Payments',
        message: 'Customer asked when an escrowed payment is released after a completed session.',
        status: 'Resolved',
        createdAt: '2026-04-24T15:30:00.000Z',
        source: 'chatbot',
      },
      {
        id: 'complaint-2',
        topic: 'Scheduling',
        message: 'Provider arrived late and the customer requested a reschedule window.',
        status: 'Open',
        createdAt: '2026-04-25T09:10:00.000Z',
        source: 'manual',
      },
    ],
  }
}
